### ISSUE TITLE
Deploy to github pages

### ISSUE THREAD

**Issue by AbraaoAlves** [kevinDsousa/Presentations#1]
## Make your friends life easier! 
---

# Proposal

Create a `.github/workflows/deploy.yml` file to dispatch actions to:
- build project
- delivery builder files to `github pages` 

Here is a sample how to do it:

``` yml
name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build project
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist # pay attention here dist folder
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # use dist folder with builder files
```
